# Generated by Django 5.2 on 2025-07-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineinventory',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
