# Generated by Django 5.2 on 2025-07-22 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_about_achievement_mission_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.teammember'),
        ),
    ]
