# Generated by Django 5.2 on 2025-07-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_image_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.about'),
        ),
    ]
