# Generated by Django 5.2 on 2025-07-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_image_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('patients_served', models.CharField(max_length=50)),
                ('satisfaction_rate', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home About',
                'verbose_name_plural': 'Home About Sections',
            },
        ),
        migrations.CreateModel(
            name='HomeAboutAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('Award', 'Award'), ('Users', 'Users'), ('Heart', 'Heart'), ('Activity', 'Activity'), ('Shield', 'Shield'), ('Star', 'Star'), ('CheckCircle', 'CheckCircle'), ('Trophy', 'Trophy'), ('UserCheck', 'UserCheck'), ('HeartPulse', 'HeartPulse')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home About Achievement',
                'verbose_name_plural': 'Home About Achievements',
            },
        ),
        migrations.CreateModel(
            name='MissionStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mission Statement',
                'verbose_name_plural': 'Mission Statements',
            },
        ),
    ]
