# Generated by Django 5.2 on 2025-09-19 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blooddonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonationinterest',
            name='donation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_interest', to='core.blooddonation'),
        ),
    ]
