# Generated by Django 5.2 on 2025-09-23 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_event_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodCollectionLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='collection_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bloodcollectionlocation'),
        ),
    ]
