# Generated by Django 5.2 on 2025-09-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bloodcollectionlocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='collection_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='BloodCollectionLocation',
        ),
    ]
