# Generated by Django 5.2 on 2025-09-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_bloodrequest_collection_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
