# Generated by Django 5.2 on 2025-09-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pdfdocument_remove_blooddonor_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='specialty',
            new_name='session',
        ),
    ]
